"""changed address table

Revision ID: 19b3fa78dc72
Revises: ea0c78507f47
Create Date: 2024-09-10 16:56:28.534696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b3fa78dc72'
down_revision: Union[str, None] = 'ea0c78507f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('Address', sa.String(), nullable=False))
    op.drop_column('addresses', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'Address')
    # ### end Alembic commands ###
