"""changed product table

Revision ID: 223c5a0a492f
Revises: b2c5ea46af6c
Create Date: 2024-09-17 13:40:39.722944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223c5a0a492f'
down_revision: Union[str, None] = 'b2c5ea46af6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('has_variants', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'has_variants')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
