"""created new column in the order table customer_email

Revision ID: 8df66d551615
Revises: eecf1d3ee7e9
Create Date: 2024-09-15 12:53:35.248472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df66d551615'
down_revision: Union[str, None] = 'eecf1d3ee7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###
