"""changed nullable of variant_id in the orders items

Revision ID: c0c20e56656e
Revises: 5612bcfebe59
Create Date: 2024-09-17 14:17:21.586301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c20e56656e'
down_revision: Union[str, None] = '5612bcfebe59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'variant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
