"""added currency column

Revision ID: ce8459d054be
Revises: 96b5f4cb3241
Create Date: 2024-09-17 16:18:36.204290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8459d054be'
down_revision: Union[str, None] = '96b5f4cb3241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('products', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'currency')
    op.drop_column('products', 'currency')
    op.drop_column('orders', 'currency')
    # ### end Alembic commands ###
