"""changed the column name in the order table customer_email

Revision ID: fae89c12d44d
Revises: 8df66d551615
Create Date: 2024-09-15 13:02:29.852454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae89c12d44d'
down_revision: Union[str, None] = '8df66d551615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_email', sa.String(), nullable=True))
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'customer_email')
    # ### end Alembic commands ###
